window.debug = false;
var config = {
    urlArgs: "==version==",
    waitSeconds: 0,
    baseUrl: 'js',
    paths: {
        'toolkit' : "../../toolkit",
        'component' : "../../toolkit/component",
        'echartGalleryJs': "../../toolkit/echarts-gl/echarts-gl.min",
        'ace': '../../node_modules/ace-builds/src-noconflict/ace',
        'ace-language' : '../../node_modules/ace-builds/src-noconflict/ext-language_tools',
        'keyboardJS': '../../node_modules/keyboardjs/dist/keyboard',
        'moment': '../../node_modules/moment/min/moment.min',
        'jquery': '../../node_modules/jquery/dist/jquery.min',
        'ui-router': '../../node_modules/angular-ui-router/release/angular-ui-router',
        'angular': '../../node_modules/angular/angular.min',
        'ng-dialog': '../../node_modules/ng-dialog/js/ngDialog',
        'angular-route': '../../node_modules/angular-route/angular-route.min',
        'angular-resource': '../../node_modules/angular-resource/angular-resource.min',
        'angular-animate': '../../node_modules/angular-animate/angular-animate.min',
        'angular-growl': '../../node_modules/angular-growl-v2/build/angular-growl.min',
        'angular-style': '../../toolkit/angular-custom/angular-style',
        'angular-dialogue': '../../toolkit/angular-custom/angular-dialogue',
        'angular-popup': '../../toolkit/angular-custom/angular-popup',
        'bootstrap-datetimepicker': '../../node_modules/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min',
        'angular-file-upload': '../../node_modules/angular-file-upload/dist/angular-file-upload.min',
        'clipboard': '../../node_modules/clipboard/dist/clipboard.min',
        'datatables.net': '../../node_modules/datatables.net/js/jquery.dataTables',
        'datatables.net-bs': '../../node_modules/datatables.net-bs/js/dataTables.bootstrap',
        'datatables.net-buttons': '../../node_modules/datatables.net-buttons/js/dataTables.buttons',
        'datatables.net-buttons-bs': '../../node_modules/datatables.net-buttons-bs/js/buttons.bootstrap',
        'datatables.buttons.html5': '../../node_modules/datatables.net-buttons/js/buttons.html5',
        'datatables.net-select': '../../node_modules/datatables.net-select/js/dataTables.select.min',
        'bootstrap-daterangepicker': '../../node_modules/bootstrap-daterangepicker/daterangepicker',
        'jquery-ui': "../../node_modules/components-jqueryui/jquery-ui",
        'jquery-cookie': "../../node_modules/jquery.cookie/jquery.cookie",
        'jquery-session': "../../toolkit/jquery-session",
        'underscore': '../../node_modules/underscore/underscore',
        'domReady': '../../node_modules/requirejs-domready/domReady',
        'zrColor': '../../../node_modules/zrender/src/tool/color',
        'slick': '../../node_modules/slick-carousel/slick/slick.min',
        'slimscroll': '../../node_modules/jquery-slimscroll/jquery.slimscroll.min',
        'dark': '../../node_modules/echarts/theme/dark',
        'macarons': '../../node_modules/echarts/theme/macarons',
        'spectrum': '../../node_modules/spectrum-colorpicker/spectrum',
        'echarts': '../../node_modules/echarts/dist/echarts.min',
        'bootstrap': '../../node_modules/bootstrap/dist/js/bootstrap.min',
        'bootstrap-dialog': '../../node_modules/bootstrap3-dialog/dist/js/bootstrap-dialog.min',
        'bootstrap-multiselect': '../../node_modules/bootstrap-multiselect/dist/js/bootstrap-multiselect',
        'table2excel' : '../../node_modules/jquery-table2excel/dist/jquery.table2excel',
        'bmap': '../../node_modules/echarts/dist/extension/bmap.min',
        'select2': '../../node_modules/select2/dist/js/select2.min',
        'd3': '../../node_modules/d3/dist/d3',
        'jwplayer': '../../toolkit/jwplayer',
        'jwplayer.html5': '../../toolkit/jwplayer.html5',
        'lodash': '../../node_modules/lodash/index',
        'rappid-joint': '../../toolkit/rappid/dist/rappid',
        'config': 'config',
        'directive': 'directives/index',
        'service': 'services/index',
        'filter': 'filters/index',
        'value': 'values/index',
        'index-app': '../../toolkit/admin-lte/app',
        'controller': 'controllers/index',
        'optionDataHandler': 'toolkit/optionDataHandler',
        'profile': 'toolkit/profile',
        'modelPanel': 'toolkit/modelPanel',
        'setting': 'toolkit/setting',
        'dom': 'toolkit/dom',
        'ckplayer': '../../toolkit/ckplayer/ckplayer',
        'ezuikit' : '../../toolkit/ezuikit',
        'static': 'toolkit/static',
        'codeMirrorEditor': 'toolkit/codeMirror',
        'free-board': '../../toolkit/component/free-board',
        'colorPicker': 'toolkit/colorPicker',
        'grid_controller': 'toolkit/grid_controller',
        'echart_creator': 'toolkit/echart_creator',
        'optionEdit': 'toolkit/optionEdit',
        'commonlib': '../../toolkit/commonLib/js/lib/commonlib',
        'Array': '../../toolkit/commonLib/js/lib/Array',
        'sparkline': '../../toolkit/sparkline/dist/jquery.sparkline.min',
        'tools': '../../toolkit/tools',
        'app': 'app',
        'svgcharts': '../../toolkit/svgcharts/svgcharts',
        'configs': '../../toolkit/configs',
        'backbone': '../../node_modules/backbone/backbone',
        'baiduMap': 'https://api.map.baidu.com/getscript?v=2.0&ak=eMekSXxqG1j2wLM57RFN61l8T6eB1EDx&services=',
        'BMapLib': '../../toolkit/component/BMapLib',
        'contextmenu': '../../toolkit/contextmenu/contextmenu',
        'handsontable': '../../node_modules/handsontable/dist/handsontable.full',
        'loader': '../../js/loader',
        'simulate': '../../toolkit/component/simulate',
        'simulate_time': '../../toolkit/component/simulate_time',
        'commonMethod': '../../toolkit/component/commonMethod',
        'dropdowntree': '../../toolkit/component/dropdowntree',
        'autocomplete': '../../toolkit/component/autocomplete',
      'clock' : '../../toolkit/component/explainer/clock',
      'solution' : '../../solution/module',
      'laydate' : '../../toolkit/laydate/laydate',
      'pstree' : '../../node_modules/proudsmart-tree/dist/ps-tree',
      'jsToBeautify' : '../../node_modules/js-to-beautify/dist/jsToBeautify',

    },
    shim: {
      'ace' : { exports:'ace'},
      'ace-language' : { deps : ['ace']},
        'echart_v2': {exports: 'echarts'},
        'index-app': {deps: ['jquery', 'jquery-ui']},
        'echartGalleryJs': {deps: ['echarts']},
        'slimscroll': {
            deps: ['jquery']
        },
        'bootstrap-multiselect': {
            deps: ['jquery', 'bootstrap']
        },
        'ng-dialog': {
            deps: ['angular']
        },
        'tools': {deps: ['jquery']},
        'jquery-ui': {deps: ['jquery']},
        'jquery-cookie': {deps: ['jquery']},
        'jquery-session': {deps: ['jquery']},
        'free-board': {deps: ['jquery']},
        'contextmenu': {deps: ['jquery']},
        'spectrum': {deps: ['jquery']},
        'angular': {exports: 'angular'},
        'configs': {
            deps: ['jquery']
        },
        'jwplayer': {
            deps: ['jquery']
        },
        'angular-route': {deps: ['angular']},
        'angular-resource': {deps: ['angular']},
        'angular-animate': {deps: ['angular']},
        'angular-growl': {deps: ['angular']},
        'angular-style': {deps: ['angular']},
        'angular-dialogue': {deps: ['angular']},
        'angular-popup': {deps: ['angular']},
        'angular-file-upload': {
            deps: ['angular']
        },
        'underscore': {exports: '_'},
        'zrender': {experts: 'zrender'},
        'bootstrap': {
            deps: ['jquery']
        }
    },
    deps: ['angular-bootstrap', 'tools', 'Array', 'slimscroll', 'jquery-ui', 'index-app', 'bootstrap-multiselect', 'contextmenu', 'loader', 'configs']
}
if (window.debug == true) {
    config.paths.angular = '../../toolkit/angular-for-debug'
}
require.config(config);